### ISSUE TITLE
Use of discontinuitySkipWeekends

### ISSUE THREAD

**Issue by bonzobavaria** [d3fc/d3fc-discontinuous-scale#22]
Is there anywhere to find a simple useage example for discontinuitySkipWeekends? 

My intuition would be that I could either wrap the domain,
``` 
noWeekends = discontinuitySkipWeekends(domain)
```
or just chain it onto the scale,
```
const scale = d3.scaleTime()
    .discontinuitySkipWeekends()
    .domain(timeDomain)
    .range(chartRange)
```

but nothing's working for me. I could use an example to model from.

**Comment by ColinEberhardt** [comment]
The discontinuous scale adapts a scale, allowing you to add a discontinuity provider, which describes the discontinuities (or breaks) in the scale. Here is how you can adapt a d3 time scale to skip weekends:

```
const skipWeekendScale = fc.scaleDiscontinuous(d3.scaleTime())
  .discontinuityProvider(fc.discontinuitySkipWeekends());
```

And here's a complete example:

https://bl.ocks.org/ColinEberhardt/0a5cc7ca6c256dcd6ef1e2e7ffa468d4

Try switching between the d3 time scale and the adapted, discontinuous scale, to see the difference.

**Comment by bonzobavaria** [comment]
That's perfect! Thank you very much.
