### ISSUE TITLE
The scale should filter out any ticks that fall within discontinuities

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc-discontinuous-scale#23]
Looking at this example, the scale has a gap between 5-20, however, the axis has a tick at '6'. This should be filtered out.

https://bl.ocks.org/ColinEberhardt/b60919a17c0b14d745c881f48effe681

The current tick filter implementation simply removes overlapping ticks.

**Comment by bonzobavaria** [comment]
I'm having a similar problem with using d3.scaleTime() with discontinuitySkipWeekends(). The timeline shows Sun and Mon removed and still shows Sat. Do you know if this is likely the same issue? 

![exclude_weekends](https://user-images.githubusercontent.com/21287248/29580548-01ceb780-873c-11e7-8d40-cbf3d1e32c65.PNG)
![with_weekends](https://user-images.githubusercontent.com/21287248/29580549-01cf37c8-873c-11e7-9f8f-f9aa003d3b3d.PNG)

**Comment by ColinEberhardt** [comment]
Yes, that's the same issue. The current tick logic 'clamps down' each tick value, then removes duplicates. As a result a tick that is within a discontinuity may still be rendered. In some senses this is correct, but confusing for the user.

We should make fixing this a priority!
